### ISSUE TITLE
Supported OS and required config

### ISSUE THREAD

**Issue by martenjacobs** [balena-io-playground/balena-fin-firmata-flash#5]
Hi,

I've been trying to get the `v1.1-beta2` branch of this repo to work with my Fin 1.1, but after tinkering until I can get the container to my device through balenaCloud and deploying the firmware successfully (I think), I'm not able to get a connection to the coprocessor as there's no `ttyS0` available on my device. From the schematics I see GPIOs 32 and 33 should be used, which means switching them to ALT3 or ALT5 (for UART0 or 1, respectively), but I don't think this is done by the balenaFin device overlay. Is there any additional configuration required to get this to work? I'm using the development version of balenaOS 2.36.0+rev2.

Thanks, 
Marten

**Comment by martenjacobs** [comment]
I tried changing the port in the script to ttyAMA0, which I understand should be connected to pins 32 and 33 in the default configuration (which connects to the bluetooth modem on a normal Pi3), but when I do that the device just waits indefinitely after printing `Checking Firmata version...`

**Comment by rohfle** [comment]
I have the following extras in my config.txt file... I think you only need `enable_uart=1` in later versions of BalenaOS as the other config is included in dtb files
```
enable_uart=1
dtparam=i2c_arm=on
dtoverlay=i2c-gpio,bus=3,i2c_gpio_sda=43,i2c_gpio_scl=42
```

Docs: https://www.balena.io/docs/learn/develop/hardware/i2c-and-spi/#serial


Note changes to the config.txt file need to be done before first boot... See https://www.balena.io/docs/reference/OS/advanced/#configtxt

**Comment by martenjacobs** [comment]
From what I understand it should work when I set these through the balenaCloud console too, right? FWIW, `enable_uart` was set to 1 by default, I guess that's because I didn't create a RPi application but a balenaFin application from the console. 

I did add the `i2c-gpio`-overlay you mentioned, although I think from looking at the [overlay file](https://github.com/raspberrypi/linux/blob/rpi-4.20.y/arch/arm/boot/dts/overlays/balena-fin-overlay.dts), this a) has nothing to do with the problem and b) is pretty much how it's set up by default.
The contents of my `config.txt` are now:
```
dtoverlay=balena-fin
dtoverlay=i2c-gpio,bus=3,i2c_gpio_sda=43,i2c_gpio_scl=42
disable_splash=1
dtparam=i2c_arm=on
dtparam=spi=on
dtparam=audio=on
enable_uart=1
gpu_mem=16
```

Still, there's no entry for `/dev/ttyS0` and when I try to run `main.js` with `ttyAMA0` it hangs.

**Comment by martenjacobs** [comment]
For completeness, here are the logs from my container deploying the firmware to the coprocessor. I see one error in there but everything seems to complete fine after that.

```
download latest firmata firmware from github...
placing firmata.hex into firmware dir...
toggling co-processor mux to flash mode...
Opening screen terminal
Trying ::1...
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Open On-Chip Debugger
> reset halt
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0fe10000 msp: 0x20000400
> program firmware/bootloader.s37
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0fe10000 msp: 0x20000400
** Programming Started **
detected part: EFR32MG1B Blue Gecko, rev 151
flash size = 256kbytes
flash page size = 2048bytes
Padding image section 0 at 0x00000614 with 492 bytes
** Programming Finished **
> reset halt
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0fe10000 msp: 0x20000400
> program firmware/firmata.hex
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0fe10000 msp: 0x20000400
** Programming Started **
SWD DPIDR 0x2ba01477
Failed to read memory at 0x400e001c
Failed to erase page 5
** Programming Finished **
> reset run
> Connection closed by foreign host.
closing the openocd process...
toggling co-processor mux to communication mode...
RUN $ node main.js, to start firmata checks
```

**Comment by rohfle** [comment]
I remember having a similar issue... I also went down the ttyAMA0 track and got confused. But ttyS0 is definitely the right interface.

Maybe what I did to get it working is this:
- Prevented start.sh from running automatically in Dockerfile.template
- SSH'd in and ran start.sh manually to flash
- Rebooted the balenafin to get serial working

**Comment by martenjacobs** [comment]
I already did a similar thing by setting [the STOP env var](https://github.com/balena-io-playground/balena-fin-firmata-flash/blob/4621718bdf0c223d4af2f70311b6d1230bd0a113/app/start.sh#L1). This prevents start.sh to actually do anything so it goes into sleep immediately.

**Comment by martenjacobs** [comment]
Okay, so I found [this](https://www.raspberrypi.org/forums/viewtopic.php?t=197856). I've been doing some tests with Raspbian, and am now able to make ttyS0 appear with these boot config files:

`config.txt`
```
dtoverlay=balena-fin
enable_uart=1
dtoverlay=uart1,txd1_pin=32,rxd1_pin=33
```

`cmdline.txt`
```
dwc_otg.lpm_enable=0 console=tty1 8250.nr_uarts=1 root=PARTUUID=43775c8c-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
```

these are the important parts:
`dtoverlay=uart1,txd1_pin=32,rxd1_pin=33`
`8250.nr_uarts=1`

I will move back to balenaOS and report back whether I can now successfully work with the coprocessor

**Comment by martenjacobs** [comment]
After the last comment, I ran into issues again, in that I didn't get any kind of reliable connection to the coprocessor over serial. After a LOT of testing, I found out that I needed to fix the CPU speed with `core_freq=250` in `config.txt` in order to use ttyS0, as it doesn't have its own clock.

**Comment by martenjacobs** [comment]
I've found out how to use UART0 to connect to the coprocessor, I'm going to write up a PR for the documentation
